project:
  type: website
  output-dir: docs

website:
  title: "FINANCIAL & ECONOMIC ANALYSIS"
  navbar:
    background: "#FFD700"
    left: 
      - "Blog by Ngoni Matereke"
    navbar-hl: "#000000"
    right:
      - icon: linkedin
        href: https://linkedin.com/
      - icon: instagram
        href: https://instagram.com
format:
  html:
    theme:
      light: flatly 
      dark: darkly
    
    css: styles.css

editor: visual

