project:
  type: website
  output-dir: docs

website:
  title: "EVERYTHING ABOUT MONEY"
  navbar:
    background: "#FFD700"
    left: 
      - "Blog by Ngoni & Tari"
    right:
      - about.qmd
      - icon: linkedin
        href: https://linkedin.com/
      - icon: instagram
        href: https://instagram.com
format:
  html:
    theme:
      light: cosmo 
      dark: darkly
    
    css: styles.css

editor: visual

